server.port=9830
spring.application.name=bookingService
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=cinebook
spring.data.mongodb.auto-index-creation=true

spring.kafka.consumer.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
spring.kafka.consumer.group-id=booking-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=3

booking.reservation.expiry-minutes=10
booking.max-seats-per-booking=10
