spring.application.name=imageService
server.port=9811

aws.s3.bucket=${AWS_S3_BUCKET_NAME:expandable-snackbox-e-38el}
aws.region=${AWS_DEFAULT_REGION:auto}
aws.access-key=${AWS_ACCESS_KEY_ID:tid_irCmMVa_RPdrjRXzfeKjYHMQMHUYFmAgQxTuKaQwFvfZItUffe}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:tsec_FP6jc_uQ_s6xeuhIC5MmdxDF5X2vveUXPg2kk2ihLnyqbYaXLqGRTXloaFrksVyqpXeVC6}
