server.port=9820
spring.application.name=movieService
spring.mongodb.uri=${MONGO_URL}
spring.mongodb.database=cinebook

aws.s3.region=${AWS_DEFAULT_REGION:ap-south-1}
aws.s3.access-key=${AWS_ACCESS_KEY_ID}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.bucket=${AWS_S3_BUCKET_NAME:cinebook-object-storage}


# Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST}:${KAFKA_PORT}
app.kafka.topic.screen-layout-create-update=screen-layout-create-update
app.kafka.topic.screen-layout-delete=screen-layout-delete
app.kafka.group-id=booking-service-group

