server.port=9820
spring.application.name=movieService
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=cinebook

aws.s3.bucket=cinebook-object-storage
aws.s3.region=ap-south-1
aws.s3.access-key=${AWS_S3_ACCESS_KEY}
aws.s3.secret-key=${AWS_S3_SECRET_KEY}

# Kafka
spring.kafka.bootstrap-servers=switchyard.proxy.rlwy.net:55146
app.kafka.topic.screen-layout-create=screen-layout-create
app.kafka.group-id=booking-service-group
