FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install axios

COPY . .
RUN npm run build

EXPOSE 80

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "80"]